repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: detect-private-key
      - id: check-case-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        name: ruff lint
        args: [--fix, --exit-non-zero-on-fix]
        files: ^auth-server/.*\.py$
      - id: ruff-format
        name: ruff format
        files: ^auth-server/.*\.py$

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        name: black formatter
        files: ^auth-server/.*\.py$
        args: [--line-length=88]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort import sorting
        files: ^auth-server/.*\.py$
        args: [--profile=black]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: bandit security check
        files: ^auth-server/.*\.py$
        args: [--configfile=auth-server/pyproject.toml]
        exclude: ^auth-server/(tests|migrations)/.*

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        name: mypy type checking
        files: ^auth-server/app/.*\.py$
        args: [--config-file=auth-server/pyproject.toml]
        additional_dependencies:
          - fastapi
          - sqlalchemy
          - pydantic
          - types-redis
          - types-PyJWT

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest tests
        entry: bash
        language: system
        args:
          - -c
          - |
            if [[ $(git diff --cached --name-only | grep -E '^auth-server/.*\.py$') ]]; then
              cd auth-server && ENVIRONMENT=test uv run pytest tests/ --tb=short -q || exit 1
            fi
        pass_filenames: false
        always_run: false
        stages: [pre-commit]

      - id: no-secrets
        name: check for secrets
        entry: bash
        language: system
        args:
          - -c
          - |
            # Check for common secret patterns
            if git diff --cached --name-only | xargs grep -l -E "(api[_-]?key|secret[_-]?key|password|token).*=.*['\"][^'\"]{10,}" 2>/dev/null; then
              echo "❌ Potential secrets detected in staged files"
              exit 1
            fi
        pass_filenames: false

      - id: auth-server-only
        name: auth server file changes
        entry: bash
        language: system
        args:
          - -c
          - |
            # Only run auth-server checks if auth-server files changed
            if [[ $(git diff --cached --name-only | grep -E '^auth-server/') ]]; then
              echo "✅ Auth server files detected, running full checks"
            fi
        pass_filenames: false
        always_run: true

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [pytest-check, no-secrets]  # Skip local hooks in CI
  submodules: false
