[project]
name = "Ai0S"
version = "0.1.0"
description = "Agentic AI OS Control System - Voice-controlled desktop automation"
requires-python = ">=3.11"
dependencies = [
    # Core Environment & Configuration
    "python-dotenv>=1.0.0",
    "click>=8.1.0",
    
    # AI Processing
    "google-generativeai==0.8.3",
    "groq>=0.4.0",
    
    # Desktop GUI
    "customtkinter>=5.2.2",
    "pillow>=10.0.0",
    
    # Audio Processing
    "sounddevice>=0.4.6",
    "scipy>=1.11.0", 
    "numpy>=1.24.0,<2.0.0",
    
    # Desktop Automation
    "pyautogui>=0.9.54",
    "pynput>=1.7.6",
    
    # System & Network
    "psutil>=5.9.6",
    "requests>=2.31.0",
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
    "websockets>=12.0.0",
    
    # Data Processing
    "pydantic>=2.0.0",
    
    # AI Orchestration
    "langgraph>=0.2.0",
    "langchain-core>=0.3.0",
]

[project.optional-dependencies]
windows = [
    # Windows-specific only
    "pywin32>=306",
    "wmi>=1.5.1",
]

dev = [
    # Development tools
    "pytest>=7.4.0",
    "ruff>=0.1.6",
    "black>=23.11.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
ai0s = "src.launcher:main"

[tool.ruff]
target-version = "py311"
line-length = 100