name: 🐛 Bug Report
description: Create a report to help us improve the Auth Server
title: "[BUG] "
labels: ["bug", "auth-server"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for the Kali AI-OS Authentication Server!

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the auth server is affected?
      options:
        - Authentication (login/register)
        - API Key Management
        - Database Operations
        - Docker/Deployment
        - Security Features
        - Tests
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - OS: [e.g., Ubuntu 22.04, Windows 11, macOS 13]
        - Python version: [e.g., 3.11.5]
        - uv version: [e.g., 0.4.18]
        - Docker version: [e.g., 24.0.6]
        - Auth server version/commit: [e.g., main, v1.0.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please copy and paste any relevant log output
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true