name: Kali AI OS CI/CD

on:
  push:
    branches: [ master, main, develop ]
    paths:
      - 'kali-ai-os/**'
      - '.github/workflows/kali-ai-os-ci.yml'
  pull_request:
    branches: [ master, main, develop ]
    paths:
      - 'kali-ai-os/**'
      - '.github/workflows/kali-ai-os-ci.yml'

defaults:
  run:
    working-directory: kali-ai-os

jobs:
  lint-and-format:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.18"
        enable-cache: true

    - name: Set up Python
      run: uv python install

    - name: Install PortAudio
      run: sudo apt-get update && sudo apt-get install -y portaudio19-dev

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run ruff linter
      run: uv run ruff check . --output-format=github

    - name: Run black formatter check
      run: uv run black --check --diff .

    - name: Run isort import sorting check
      run: uv run isort --check-only --diff .

    - name: Run mypy type checking
      run: uv run mypy src/ --ignore-missing-imports
      continue-on-error: true

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: lint-and-format

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.18"
        enable-cache: true

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          portaudio19-dev \
          xvfb \
          x11-utils \
          wmctrl \
          xdotool \
          scrot \
          imagemagick \
          libgl1-mesa-dri \
          libgl1-mesa-glx \
          libegl1-mesa \
          libglib2.0-0 \
          libsm6 \
          libxext6 \
          libxrender-dev \
          libgomp1 \
          libgtk-3-0 \
          libqt5widgets5 \
          dbus-x11

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run unit tests (non-desktop)
      run: |
        export ENVIRONMENT=test
        uv run pytest tests/auth/ tests/integration/ -v --tb=short
      env:
        ENVIRONMENT: test

    - name: Run desktop tests with virtual display
      run: |
        export ENVIRONMENT=test
        export DISPLAY=:99
        xvfb-run -a -s "-screen 0 1920x1080x24 -ac +extension GLX +render -noreset" \
          uv run pytest tests/desktop/ -v --tb=short \
          --disable-warnings \
          -x
      env:
        ENVIRONMENT: test
        DISPLAY: :99

    - name: Upload coverage reports
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: kali-ai-os
        name: kali-ai-os-coverage
      continue-on-error: true
